import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Belogoo App",
  description: "Generated by Belogoo",
  icons: {
    icon: [
      {
        url: "/favicon/b.ico",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/images/blog.ico",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white dark:bg-slate-950 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="pt-20 px-5 md:container md:mx-auto">{children}</div>
      </body>
    </html>
  );
}
